---
- name: Add kubernetes repo
  ansible.builtin.yum_repository:
    name: Kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
    file: kubernetes.repo
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: yes

- name: Install kubelet
  ansible.builtin.dnf:
    name:
      - kubelet
    state: present