---
- name: Add kubernetes repo
  ansible.builtin.yum_repository:
    name: Kubernetes
    description: Kubernetes
    baseurl: https://pkgs.k8s.io/core:/stable:/v1.29/rpm/
    file: kubernetes.repo
    gpgkey:
      - https://pkgs.k8s.io/core:/stable:/v1.29/rpm/repodata/repomd.xml.key
    gpgcheck: yes

- name: Install kubelet
  ansible.builtin.dnf:
    name:
      - kubelet
    state: present
