---
- name: Verify
  hosts: all
  gather_facts: true
  vars:
    kubelet_download_dir: "/usr/local/bin"
  tasks:
    - name: Find the kubelet file
      ansible.builtin.stat:
        path: "{{ kubelet_download_dir }}/kubelet"
      register: kubelet_file

    - name: Print stat info
      ansible.builtin.debug:
        msg: "{{ kubelet_file.stat }}"

    - name: Assert that kubelet exists
      ansible.builtin.assert:
        that: kubelet_file.stat.exists

    - name: Assert that kubelet is executable
      ansible.builtin.assert:
        that: kubelet_file.stat.executable